project_id = "bfnlvdbswhjlpzdfwznz"

[functions.submit-review]
verify_jwt = false

[functions.admin-list-subscribers]
verify_jwt = false

[functions.admin-manage-subscription]
verify_jwt = false

[functions.admin-revenue-stats]
verify_jwt = false

[functions.public-invoice]
verify_jwt = false

[functions.get-review-request]
verify_jwt = false

[functions.public-quote]
verify_jwt = false

[functions.approve-quote]
verify_jwt = false